# https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz

- name: Setup node exporter
  ansible.builtin.unarchive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

- name: copy systemD exporter
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: start node exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: true
    daemon_reload: true
