- name: update prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alerting configuration
  ansible.builtin.template:
    src: { { item } }
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"


- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true
    daemon_reload: true

- name : check if prometheus is started
  ansible.builtin.shell: netstat -lntp | grep 9090


