
- name: create Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Delete old App Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

# Download from S3

#- name: Downloading and extract {{ component }} Content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

# Download from Nexus
- name: Downloading and extract {{ component }} Content
  ansible.builtin.unarchive:
    src: http://admin:admin123@nexus.kalluriravidevops71.online:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes