- name: Setup-Hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: install exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: exporter
  when: node_exporter

- name: install filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat
  when: filebeat