groups:
  - name: roboshop
    rules:
      - alert: serverdown
        expr: up < 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: serverdown

      - alert: CPU Usage
        expr: 100 - (avg by (name) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100) > 80
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: CPU Usage